### ISSUE TITLE
nullpointerexception log spam when in nether

### ISSUE THREAD

**Issue by sreny1** [eerussianguy/BlazeMap#16]
playing the pack all the mods gravitas version 1.3

whenever i'm in the nether i get this spammed in my log:
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "rock" is null
	at TRANSFORMER/cartography@0.3.0-dev/lordfokas.cartography.feature.data.rock.RockClusterRealm.<init>(RockClusterRealm.java:17)
	at TRANSFORMER/cartography@0.3.0-dev/lordfokas.cartography.feature.data.rock.RockClusterStore.lambda$getDataPool$3(RockClusterStore.java:41)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at TRANSFORMER/cartography@0.3.0-dev/lordfokas.cartography.feature.data.rock.RockClusterStore.getDataPool(RockClusterStore.java:39)
	at TRANSFORMER/cartography@0.3.0-dev/lordfokas.cartography.feature.data.rock.RockLayerProcessor.execute(RockLayerProcessor.java:30)
	at TRANSFORMER/blazemap@0.4.11-dev/com.eerussianguy.blazemap.engine.CartographyPipeline.lambda$processMasterData$10(CartographyPipeline.java:213)
	at TRANSFORMER/blazemap@0.4.11-dev/com.eerussianguy.blazemap.engine.async.AsyncDataCruncher.work(AsyncDataCruncher.java:78)
	at TRANSFORMER/blazemap@0.4.11-dev/com.eerussianguy.blazemap.engine.async.AsyncDataCruncher.loop(AsyncDataCruncher.java:60)

**Comment by Gaelmare** [comment]
This is log spam from Cartography add-on, not BlazeMap.
